### ISSUE TITLE
plugin is not connecting with HomeAssistant - all actions have empty dropdowns

### ISSUE THREAD

**Issue by tommasodargenio** [jaybz/TP-HomeAssistant#10]
Hi, I've just found about your plugin and since I use Home Assistant a lot this is a nice addition as I have to use some workaround via CMD script using curl etc to interface TPP with Home Assistant.

I've installed and configured it as directed (with the local URL and a proper token). However when I go to edit a button in TP and use any of the plugin's actions all the dropdowns (i.e. to select entities/devices) are empty. I've checked the log and I can see an exception been raised when attempting to login.

You can find the log [here](https://pastebin.com/6p5Bhbja)

I'd appreciate it if you could provide some help, I'll fork the code later on and debug it myself, if I find the solution I'll comment on this and perhaps send a PR.

Cheers

**Comment by jaybz** [comment]
The logs are indicating an issue with logging in. That could be an incorrect long-lived access token or a connection issue. You can try the following:

- Try re-entering the long-lived access token and make sure you're not accidentally pasting extra characters into the plugin settings. I haven't tested if Touch Portal trims plugin settings and I haven't bothered putting in input trimming code in the plugin.
- Check your firewall settings to make sure that TP-HomeAssistant.exe is allowed to connect to your Home Assistant instance. The plugin makes two different TCP connections (one to Touch Portal and another to Home Assistant) which may potentially cause the firewall prompts to only allow one of them but not the other.
- Try accessing the Home Assistant web interface using its IPv4 address from a browser on the computer you're using Touch Portal from. Use the private IPv4 address if you're running Touch Portal in the same network as your Home Assistant instance. This is to make sure there aren't any routing issues.
- Try using the IPv4 address in the Home Assistant URL in the plugin settings if you're currently using the hostname. As with above, use the private IPv4 address if you're running Touch Portal in the same network as your Home Assistant instance. This is to make sure that there aren't any DNS issues or that the plugin isn't trying to use IPv6 instead. I don't see any reason why the plugin won't be able to use IPv6 if available, but IPv6 adds another layer of potential issues and I haven't tested IPv6 thoroughly on the plugin yet.
- Try using http instead if possible. I have not tested the plugin with https yet.

If none of those work, I've just pushed code into the develop branch that improves logging during authentication. If you don't mind building from that branch yourself, I'd recommend using that to debug the issue. Otherwise, I can publish a dev build you can try. I haven't thoroughly tested that code though so usual beta software disclaimers apply.

**Comment by jaybz** [comment]
Closing issue as I haven't received any further response. Please re-open if necessary.

**Comment by cooltings** [comment]
Hi, 
I am having the same issue on macOS (M2 chip) with all empty dropdowns:

![Image](https://github.com/user-attachments/assets/d2cf447c-77ad-4611-be04-3db12f3d4c78)

```
20:05:08.251 - [LOG  ] [Plugin System] Executing plugin service: /usr/local/share/dotnet/dotnet /Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/TP-HomeAssistant.dll
20:05:08.263 - [ERROR] [ome Assistant Plugin] Failed to load /Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/libhostpolicy.dylib, error: dlopen(/Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/libhostpolicy.dylib, 0x0001): tried: '/libhostpolicy.dylib' (no such file), '/Applications/TouchPortal.app/Contents/app/libhostpolicy.dylib' (no such file), '/Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/libhostpolicy.dylib' (no such file), '/Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
20:05:08.264 - [ERROR] [ome Assistant Plugin] An error occurred while loading required library libhostpolicy.dylib from [/Users/-redacted-/Documents/TouchPortal/plugins/TP-HomeAssistant/]
```

**Comment by cooltings** [comment]
![Image](https://github.com/user-attachments/assets/0139d760-93ad-44dd-b8ef-ed9590c3a7f1)

**Comment by jaybz** [comment]
@cooltings Unfortunately, I do not have access to any M series Macs as of this time so I am unable to provide any support for them at this time. Based on the error message you're getting, the only thing I can suggest is that you make sure you're using the TPP file for the OS X version and not the Win version. The file should be named TP-HomeAssistant-**osx**-x64-<version/tag>.tpp.

If that still doesn't work, ping me on the TouchPortal discord on the Home Assistant channel. There may be one more thing I can try, but it's mostly a shot in the dark than anything else.
