### ISSUE TITLE
Is there any way to get events?

### ISSUE THREAD

**Issue by lgander** [jaybz/TP-HomeAssistant#30]
Installed this plugin a couple of days ago and its working great. Thanks for this!
I'd like to know if there is any way to get events, so for example: if I turn a light ON with an external switch, the icon of that light in TouchPortal changes.

**Comment by jaybz** [comment]
Right now, it depends on your device. Because the plugin uses Home Assistant's REST API, there isn't a way (at least none that is documented) for the plugin to subscribe to events. I will have to migrate to websockets to do that I believe. However, if your device is not a stateless device (meaning it provides states like the on/off state) you can use Touch Portal's "When plug-in state changes" event to respond to a device's state changes and use the change button visuals action for example, to change the button's icon or even background color. Below is an example of how to do that.

![image](https://user-images.githubusercontent.com/10665566/233126961-7867f0e2-b592-42d7-b50d-fef412401100.png)

For more information on Touch Portal's events and actions though, I recommend going to Touch Portal's Discord server instead.

**Comment by lgander** [comment]
Works great. Thanks a lot!
